### PR TITLE
New design

### PR DESCRIPTION
**Pull request by benhalverson**

### CODE REVIEW

**Comment by josh64x2** [comment]
Thanks @benhalverson  :)

The bottom of the site looks a bit odd: 
pasted image at 2017_10_08 05_49 pm


And the menu at the top doesn't seem to be working - it looks like the links are broken? Anyway I'm mentioning it here so I don't forget where we are up to :)

**Comment by josh64x2** [comment]
Oh I found another couple of "issues"

The title is set incorrectly in Safari - `<title>Agency | Canvas</title>`

There is a missing resource:
 console

**Comment by benhalverson** [comment]
@josh64x2 Thanks for the update. I'll take a look at these issues this week.

**Comment by benhalverson** [comment]
> <title>Agency | Canvas</title>
What do you want the title to be? @josh64x2 
I'll also either remove the preloader or find the missing one

**Comment by josh64x2** [comment]
@benhalverson I guess just keep it like the current one for now but changed slightly to:

`ViennaRSS &#8211; The Free and Open Source RSS/Atom Reader for macOS`

**Comment by josh64x2** [comment]
@benhalverson how did the live stream go? :)

**Comment by benhalverson** [comment]
@josh64x2 The footer is fixed. Still working on the development page

**Comment by josh64x2** [comment]
@benhalverson I made some fixed and I'll create a PR into your branch.

**Comment by josh64x2** [comment]
@benhalverson I botched that last PR - i made a new one at 
https://github.com/benhalverson/viennarss.github.io/pull/2

Some things I can see we need to fix before we merge:
1. Update the screenshots
2. Reduce the size of the branch - it's huge! (I assume a bunch of files from the original theme that we don't need)

**Comment by josh64x2** [comment]
Regarding the size... it's that `temp` folder. Can we kill that off now or are you still using it for reference?

**Comment by benhalverson** [comment]
oh ya that can go. @josh64x2

**Comment by josh64x2** [comment]
OK I submitted 
https://github.com/benhalverson/viennarss.github.io/pull/3 so now all we really need to do is get some new screenshots uploaded maybe.

Or we can just merge as it is, and then update the screenshots after.

**Comment by benhalverson** [comment]
🎉 awesome

**Pull request merged**
