### PR TITLE
Mobile header fix

### LINKED ISSUE #20: Fix mobile version of the website
Main issue is the logo doesn't seem to load on mobile:

file

### PR DESCRIPTION
**Pull request by benhalverson**
Fixes #20

### CODE REVIEW

**Comment by josh64x2** [comment]
Why does this have so many commits? 😱

**Comment by benhalverson** [comment]
🤷‍♂️ no idea

**Comment by josh64x2** [comment]
can you please try and create a new branch from the current master?

**Comment by benhalverson** [comment]
#25 replaces this pull request

**Pull request closed without merging**
